### ISSUE TITLE
it doesn't work on my mac

### ISSUE THREAD

**Issue by codeek** [bestwu/gradle-dependencies-plugins-helper-plugin#1]
As i followed your guide steps and the plugin just didn't work, it's really werid.

Plugin Version:Latest version

Environment:MacOS 10.13

IDEA Version: 2017.2.5 Build #IU-172.4343.14, built on September 26, 2017

**Comment by bestwu** [comment]
Make sure `Smart Type Completion` is on.

The plugin rely on the network,make sure you can visit [https://api.bintray.com/search/packages/maven](https://api.bintray.com/search/packages/maven) and [https://plugins.gradle.org/search](https://plugins.gradle.org/search).

The Use Maven Index for search and Use Nexus for search is optional.These function is to speed up the search.You can just close these options and try again.

Is there an error log in the event log panel or anywhere else?

**Comment by codeek** [comment]
Sorry for my misunderstanding of your guide steps and the plugin works fine now.
Thanks for your useful plugin
