### ISSUE TITLE
can't work on androidstudio3.0

### ISSUE THREAD

**Issue by crazecoder** [bestwu/gradle-dependencies-plugins-helper-plugin#6]

**Comment by bestwu** [comment]
Can you describe the problem in detail?

**Comment by iulian0512** [comment]
i can confirm that it does not work in AStudio v3.0.1, the autocomplete pop-up does not show, there is no error displayed whatsoever.

**Comment by wawo00** [comment]
we need it in android studio 3.0.1!!!pls!!
