### ISSUE TITLE
冒昧的在这打扰下。请问bestwu/ewomail是删除了吗？

### ISSUE THREAD

**Issue by 809509941** [bestwu/gradle-dependencies-plugins-helper-plugin#8]
在网上看到的都是您的docker教程。本来想直接docker安装的。结果发现hub.docker上面没有bestwu/ewomail
不知道是什么原因，是否之后还会更新

**Comment by bestwu** [comment]
bestwu/ewomail 不再维护，建议通过官方方式安装。有其他问题，可通过邮件与我联系。
