### ISSUE TITLE
can't work on idea2020.2

### ISSUE THREAD

**Issue by wangtaicheng** [bestwu/gradle-dependencies-plugins-helper-plugin#9]
在2020.2 上没有显示依赖选项，也没有错误。

**Comment by bestwu** [comment]
jetbrains://idea/settings?name=Other+Settings--Gradle+Dependencies+And+Plugins+Helper 配置发一下呢

**Comment by wangtaicheng** [comment]
![image](https://user-images.githubusercontent.com/6257526/93175811-d0ca5c80-f762-11ea-8afb-837e55e73f53.png)

[idea - 副本.log](https://github.com/bestwu/gradle-dependencies-plugins-helper-plugin/files/5222974/idea.-.log)

**Comment by wangtaicheng** [comment]
> jetbrains://idea/settings?name=Other+Settings--Gradle+Dependencies+And+Plugins+Helper 配置及idea.log日志 发一下呢
知道原因了，快捷键不一样，可以close 了，谢谢
